sonar.projectKey=login-screen-trial
sonar.sources=client/src,server
sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.test.js,**/*.test.jsx,client/src/test/**
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info,server/coverage/lcov.info